### ISSUE TITLE
NXcollection is an invalid class in NXsensor

### ISSUE THREAD

**Issue by jkotan** [nexpy/nxvalidate#6]
I get  the following warning 
  `NXcollection is an invalid class in NXsensor` 

I think NXcollection is allowed below NXsensor

**Comment by rayosborn** [comment]
I have just released v0.2.0b1. Please check to see if this is still a bug.

**Comment by jkotan** [comment]
The bug is still in v0.2.0b1

**Comment by rayosborn** [comment]
I just checked the NXsensor NXDL file, and there is no mention of NXcollection and the `ignoreExtraGroups` attribute has not been set. Technically, this means that the presence of NXcollection groups in NXsensor groups is a violation. Whether this should be a violation is something to raise with the NIAC. One of the aims of NXvalidate is to trigger such discussions. It might be argued that NXcollection groups should be allowed everywhere, but I'm not sure if the current NXDL syntax has a mechanism for defining such rules.

If you think the above statement is incorrect, please explain why.

**Comment by jkotan** [comment]
According to 

https://github.com/nexusformat/definitions/blob/9059815e131dd308677d01da793b63f9d214dbb3/manual/source/design.rst?plain=1#L479-L520

NXcollection, NXdata , NXlog , ...  can appear anywhere in the NeXus hierarchy, where needed.

**Comment by rayosborn** [comment]
This should now be fixed in [v0.3.0-beta.1](https://github.com/nexpy/nxvalidate/releases/tag/0.3.0-beta.1), at least when using the definitions stored in the package. The NIAC recently approved the addition of inheritance to the NXobject class, which now means that it is possible to add fields and classes that are allowed in every base class to the NXobject NXDL file. In NXValidate, these classes include NXcollection, NXdata, NXlog, NXnote, and NXparameters. I should probably add NXtransformations, but it wasn't specified in the list I was able to compile.

This should also fix #8 and #9.

**Comment by jkotan** [comment]
Thanks. Indeed, in the newest version the issues #6, #8, #9 are fixed (if one use internal definitions)
