### ISSUE TITLE
NXlog is an invalid class in NXsample

### ISSUE THREAD

**Issue by jkotan** [nexpy/nxvalidate#8]
I get the following warning     
```  
      NXlog: /scan/sample/temperature
                NXlog is an invalid class in NXsample
```
However NXlog can be replace any field containing scanned quantities

**Comment by rayosborn** [comment]
I have just released v0.2.0b1. Please check to see if this is still a bug.

**Comment by jkotan** [comment]
The bug is also in v0.2.0b1.

**Comment by rayosborn** [comment]
Technically, the NXsample NXDL file has an entry for `temperature_log`, which is a NXlog group, whereas `temperature` has to be a field. All the NXlog groups mentioned in the base class are given a specific name. If you believe that there is a decision that all such fields can also be logs, we need to discuss at NIAC how that should be formalized.

**Comment by jkotan** [comment]
According to

https://github.com/nexusformat/definitions/blob/9059815e131dd308677d01da793b63f9d214dbb3/manual/source/design.rst?plain=1#L143-L144

any streamed field can be replaced by NXlog group. I think it is  often used in  ESS

**Comment by jkotan** [comment]
Also https://github.com/nexusformat/definitions/issues/816

**Comment by rayosborn** [comment]
You are correct that your usage has been authorized by a previous NIAC decision. We are currently discussing this very issue in the NIAC, and some are expressing a misgiving about the earlier decision. I presume you are raising this issue because you have a number of NeXus files that use this feature and would prefer that the earlier decision isn't reversed. Is that the case?

**Comment by jkotan** [comment]
Yes, we have some files already created with NXlog. Also, I must admit that NXlog class is very convenient in the case a hardware device( e.g a secop temerature sensor) provides value readouts and timestamps which do not correspond to the main scan steps.

**Comment by rayosborn** [comment]
Would you be happy if there were a restriction that the NXlog should only be used when the values are not meant to be used as a scan variable? The issue is that the log values are meant to be plotted against the time values, not to be used as independent variables in another plot. Normally, the log values are recorded asynchronously to any scan variable.

**Comment by jkotan** [comment]
Actually, we often use NXlog  to store step scan data where time contains the  exact time of readout provided by hardware.
Usually,  steps of the scans can take even a few second so it is good to store also precise readout  time.
I would say that NXdata contain plotable data fields and we could say that in NXdata should  not contain NXlog  groups but links to NXlog value and time (if needed).
